const freelancersData = [
    "Victor Ajala",
    "Wisdom Johnson",
    "John David",
    "Juliet Godwin",
    "Ridwanullah Adebowale",
    "Ile_motion",
    "Jamiu Adesina",
    "Charles Oyovbaire",
    "Ahmed Rafiat",
    "DAMILOLA TOBI ADETAYO",
    "Tamuno-omie Terry-John Ogudire",
    "Godwin Adebayo",
    "Odunayo Olawunmi",
    "David Omotosho",
    "Oluwaseun Ayobami Olusola",
    "DANIEL AMONA",
    "Theophilus Oluwape Alagbe",
    "Bashiru Kazeem Ayobamidele",
    "Olasode Adesola",
    "Charles Ikpe",
    "Akanji Michael",
    "Aminat Aliu",
    "Ganiyu Razak",
    "Sunday Odafe",
    "Oluwadamilare Godwin",
    "MIchael Karibi",
    "Prince Moses",
    "Noble Achebe-Brown",
    "Fawaz Oyelowo",
    "Adeyemo Jolaoluwa",
    "Litima Nuhu",
    "JohnJones Iwundu",
    "Ebube Onuama",
    "Samuel Tosin",
    "Edesiri Uduvwurode",
    "Godknows Ukari",
    "Ojuroungbe Quadri",
    "Joshua Okpara",
    "Adedeji Adejumo",
    "Elijah Oladimeji",
    "odutola taofeek",
    "MUYIWA OGUNYEMI",
    "Lateef Jamal Akanbi",
    "Abasiye Ibrahim",
    "Daniel Dominic",
    "Kayode Micheal",
    "Afolabi Joshua",
    "Ademola Savage",
    "Nkwocha Chinedu",
    "Sunday Babatunde",
    "Abiodun Olaniyi",
    "Samuel Ochayi",
    "Stgapy",
    "Tejiri Ejaroba",
    "Aremu Aaron Shola",
    "Ridwanullahi Popoola",
    "Blessing Akinyuwa",
    "Taiwo Damilare",
    "Eghosa Isaac",
    "Michael Babalola",
    "Raji Opeyemi Ibrahim",
    "Abdulsamad Adinoyi Nasir",
    "Omachoko Matthew",
    "Emmauel Nwankwo",
    "Peace Abayigbodi",
    "Adedasola Adeyinka",
    "Kamilu Jelil",
    "Olayiwola Abdullah",
    "Ifeanyi Ekperi",
    "Edward Banda",
    "Evans Emmanuel",
    "Osunsanya Bowale",
    "Azibatasebh Peter Oghe",
    "Adam Omobolaji",
    "Adams Benard",
    "Ihum Samuel",
    "Favour Ejekwu",
    "Dipo Oladepo",
    "Tobechukwu Aninyei",
    "Anthony King",
    "Jesse Jacob",
    "Adewole Ajibade",
    "Abraham OLAGUNJU",
    "Faruq Alayo",
    "Daniel Adeyemi",
    "Mubarak Adebayo",
    "Ademola Adeniyi",
    "Ar- dala",
    "Emmanuel Ojodun",
    "Abdulbasit Abdulraheem",
    "Eniola Ajayi-Obe",
    "Igbamosu Paul",
    "Victor Eshiet",
    "Aremu Oluwasegun",
    "Oluwafeyikemi Adetona",
    "Hassan Bakre",
    "Isaiah Ijiwade",
    "Basiru Idris",
    "Praise Ajaero",
    "Ekpo Victor",
    "Mmenim Mathias",
    "Abdoul Malik Hamidou Idi",
    "Samuel Busari",
    "Idris Babatunde",
    "Omasere Gabriel",
    "Daniel Ibuomo",
    "Igboka Ebube",
    "Comwell Aholu",
    "Joseph-Kevin Bassey",
    "Peter Onochie",
    "Samuel James",
    "Chijioke Iheanyichukwu",
    "Joshua Amondi",
    "Femi Oloyede",
    "Muhammad Ziqrullah Abdulrazaq",
    "Samuel Uti",
    "Godwin Junior",
    "Paul Ihejirika",
    "Balam Gilbert",
    "Edimek Peter",
    "Theodore Johnny",
    "Jude Ugwu",
    "Mariam Bushra",
    "Chibundu Omoji",
    "Simon Chord",
    "abodunrin kehinde"
]